#!/bin/sh

bun run --cwd action-deploy build

if ! git diff --quiet action-deploy/dist/; then
  echo "Error: action-deploy/dist is out of date. The build has been run for you - please commit the changes."
  exit 1
fi

bun run --cwd web db:generate

if ! git diff --quiet web/drizzle/migrations/; then
  echo "Error: drizzle migrations are out of date. The migrations have been generated for you - please commit the changes."
  exit 1
fi
